id = "vento"
name = "Vento"
version = "1.0.0"
schema_version = 1
authors = ["Deniz Akşimşek <deniz@aksimsek.tr>",
"Bob Rockefeller" ]
description = "Highlighting for the Vento templating language"
repository = "https://codeberg.org/dz4k/zed-vento"

[grammars.vento]
repository = "https://github.com/ventojs/tree-sitter-vento"
commit = "93939f2344ce3d2fb1f1ae4e71edb614424d5be9"
